### ISSUE TITLE
Modder credit for Summer Marine Suit Davi and others

### ISSUE THREAD

**Issue by Zipxi-m** [PhasmaExMachina/destiny-child-mods-archive#173]
Modder: Zipxim #5194
 Check discord messages on "#mods_showcase" in "destiny child global" server searching my name (@Zipxim#5194) to see my mods that I did. Im returning to my home in a few weeks (corona virus problems) and Im gonna get up to do more mods.

If u want proofs send me a message and Im gonna send you some projects file (.data .psd .kr)

Peace 

Mod link (do not change this):
https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c372_02&modHash=e63e1176a26fd1cbd3b6f213aea1fbf7&background=%23111

Mod hash (do not change this): e63e1176a26fd1cbd3b6f213aea1fbf7

**Comment by PhasmaExMachina** [comment]
I've marked https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c372_02&modHash=e63e1176a26fd1cbd3b6f213aea1fbf7&background=%23111 as yours but nothing came up when I searched both the global and international discord servers for Zipxim. If you could submit other tickets for them whenever you have time I'll make sure you're credited.

Good luck with the travels home! Stay safe!
