### ISSUE TITLE
Modder Credits for some mods

### ISSUE THREAD

**Issue by Zipxi-m** [PhasmaExMachina/destiny-child-mods-archive#175]
Thank you for adding credits to the works and for this wonderful application of yours, I gathered the links for the mods and I think it will be easier for you to add in this way.

About discord searching, just go to the search bar in DCGlobal discord and put: "from: Zipxim#5194 in: mods-showcase-💾 "

I am very happy that my mods are in your app even though they are so old.. haha 

Peace

Mods

Bathory

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c294_01&modHash=39b3fa0cc020b335de06ab5aa68dcef4&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c294_02&modHash=755a3c1c1c0a61f20a35f54357cff2f1&background=%23111

Khepri lab

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c311_00&modHash=0bcca04c9597f1a9cf98a7cc38c30400&background=%23111

PrettyMars

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c348_01&modHash=577181ae83005607bf8f15c25b7c34f0&background=%23111

Archfiend Davi and Davi

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c003_14&modHash=4df04f0a83c22b06539b189f7c33903a&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c367_01&modHash=f8aaa554594ebeb24fe328aea598819a&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c367_02&modHash=23324fd9733d5880f6eaf4e2c761d397&background=%23111

Krampus

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c246_11&modHash=17e0087b794211ca408b1ac6d731ac61&background=%23111

Eve

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c124_10&modHash=c2fab6cf21f6c0a2a703f9122436499d&background=%23111

Neban (catgirl neamhain)

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c382_01&modHash=da12fb0cae92a653750779f005923d6a&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c382_02&modHash=c9496346555decbc2fb463a5c0db152a&background=%23111

Swimsuit Davi

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c372_01&modHash=a857ef41f295d881b73401fc8dc1b3cb&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c372_10&modHash=73dbe3ecb3c27efd1cedb0af7dd11ef0&background=%23111

Isolde

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c344_01&modHash=f47b14f455e425783796f18a5b8ab4dc&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c344_01&modHash=2da26bd39e97fb6cf2d2b7b6f481c462&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c344_02&modHash=4ab657bfc826844d74e983352927e500&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c344_02&modHash=4cd8e24dd4af1bd3ba40b2909a046083&background=%23111

Neid

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c083_01&modHash=7db88246e33a0e9e74fff61d3eee94b6&background=%23111

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c083_02&modHash=00537f976cd495a6bb6188c1e710470c&background=%23111

Yuna

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c172_02&modHash=fecc48c764f5850c8c3e9fe7c5450817&background=%23111

Euros

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=c169_02&modHash=f7df9ed4a592a0afb3e186ba41370bc3&background=%23111

**Comment by PhasmaExMachina** [comment]
Done. Thanks for the links!
