### ISSUE TITLE
Add modder info to mods

### ISSUE THREAD

**Issue by PhasmaExMachina** [PhasmaExMachina/destiny-child-mods-archive#2]
The intent was always to credit individual modders, but that's a _lot_ of manual data entry. Still playing around with the best way to support this and allow people to help with this effort if they want. For one thing, mods need to be normalized into a `mods.json` file to make it easy to add additional metadata. 

Feel free to post a comment here or follow/subscribe to this issue for updates if you want to help.

**Comment by PhasmaExMachina** [comment]
This functionality is done now. It's just a matter of having people submit modder credit or me going through and manually adding them.

**Comment by HeyYou007** [comment]
NOTE !
