### ISSUE TITLE
Broken Mod

### ISSUE THREAD

**Issue by SankJinYu** [PhasmaExMachina/destiny-child-mods-archive#4]
Hi! First, thanks for your great work. As said at the DC discord (Nanyu here), want to report a broken mod. c396_02 (Oracle Kagura Warwolf).
![image](https://user-images.githubusercontent.com/68191155/87251270-b1e8da80-c440-11ea-8c35-242e1bf93737.png)

**Comment by PhasmaExMachina** [comment]
Thanks for letting me know about this. It looks like the region extraction failed on the PCK. Unfortunately I lost the original, so please feel free to open a new ticket and include the original PCK or a link to it if you ever come across it. Thanks!
